<a href="https://colab.research.google.com/github/hfeteh/hfeteh/blob/main/Students_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Student_performance_data _.csv to Student_performance_data _.csv

In [3]:
import pandas as pd
df = pd.read_csv('Student_performance_data _.csv')

In [4]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [5]:
df.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
5,1006,18,0,0,1,8.191219,0,0,1,1,0,0,0,3.084184,1.0
6,1007,15,0,1,1,15.601680,10,0,3,0,1,0,0,2.748237,2.0
7,1008,15,1,1,4,15.424496,22,1,1,1,0,0,0,1.360143,4.0
8,1009,17,0,0,0,4.562008,1,0,2,0,1,0,1,2.896819,2.0
9,1010,16,1,0,1,18.444466,0,0,3,1,0,0,0,3.573474,0.0

In [6]:
df.tail(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2382,3383,16,0,0,3,13.941823,20,0,2,0,0,0,0,1.191929,3.0
2383,3384,16,1,2,2,11.736409,18,1,4,0,0,0,0,1.810038,3.0
2384,3385,15,1,0,1,16.655581,13,1,3,0,1,0,0,2.539113,4.0
2385,3386,16,1,0,1,1.445434,20,0,3,1,1,0,0,1.395631,1.0
2386,3387,16,0,0,2,13.814021,14,0,2,0,0,0,0,2.000084,4.0
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [8]:
df.describe()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000
mean,2196.500000,16.468645,0.510870,0.877508,1.746237,9.771992,14.541388,0.301421,2.122074,0.383361,0.303512,0.196906,0.157191,1.906186,2.983696
std,690.655244,1.123798,0.499986,1.028476,1.000411,5.652774,8.467417,0.458971,1.122813,0.486307,0.459870,0.397744,0.364057,0.915156,1.233908
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1598.750000,15.000000,0.000000,0.000000,1.000000,5.043079,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.174803,2.000000
50%,2196.500000,16.000000,1.000000,0.000000,2.000000,9.705363,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.893393,4.000000
75%,2794.250000,17.000000,1.000000,2.000000,2.000000,14.408410,22.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.622216,4.000000
max,3392.000000,18.000000,1.000000,3.000000,4.000000,19.978094,29.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000

In [9]:
df.describe().round(2)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.0,2392.00,2392.00,2392.00
mean,2196.50,16.47,0.51,0.88,1.75,9.77,14.54,0.30,2.12,0.38,0.30,0.2,0.16,1.91,2.98
std,690.66,1.12,0.50,1.03,1.00,5.65,8.47,0.46,1.12,0.49,0.46,0.4,0.36,0.92,1.23
min,1001.00,15.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
25%,1598.75,15.00,0.00,0.00,1.00,5.04,7.00,0.00,1.00,0.00,0.00,0.0,0.00,1.17,2.00
50%,2196.50,16.00,1.00,0.00,2.00,9.71,15.00,0.00,2.00,0.00,0.00,0.0,0.00,1.89,4.00
75%,2794.25,17.00,1.00,2.00,2.00,14.41,22.00,1.00,3.00,1.00,1.00,0.0,0.00,2.62,4.00
max,3392.00,18.00,1.00,3.00,4.00,19.98,29.00,1.00,4.00,1.00,1.00,1.0,1.00,4.00,4.00

In [10]:
df.sample(3)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
731,1732,15,0,0,2,15.921371,27,0,2,0,1,0,0,1.084490,4.0
61,1062,17,0,0,1,17.376022,12,0,2,0,0,1,0,2.331262,3.0
2264,3265,16,0,2,1,3.423695,27,0,3,1,0,0,0,0.557549,2.0

In [11]:
df.shape

(2392, 15)

In [12]:
df.columns          	# column names

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [13]:
print(df.columns)

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [14]:
df.dtypes             	# types of each column

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

In [17]:
df['Gender']  #display column of brand

0       1
1       0
2       0
3       1
4       1
       ..
2387    1
2388    0
2389    1
2390    1
2391    1
Name: Gender, Length: 2392, dtype: int64

In [19]:
df['Age'].value_counts()       	# frequency of values

Age
15    630
16    593
17    587
18    582
Name: count, dtype: int64

In [20]:
df ['Age'].nunique()            	# number of unique values

4

In [21]:
pd.set_option('display.max_columns',None) # display all columns

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [22]:
pd.set_option('display.precision',2) # number of decimal places

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0

In [23]:
df ['Age'] 	# single column

0       17
1       18
2       15
3       17
4       17
        ..
2387    18
2388    17
2389    16
2390    16
2391    16
Name: Age, Length: 2392, dtype: int64

In [24]:
df.iloc[0] 	#dIsplay the first line

StudentID            1001.00
Age                    17.00
Gender                  1.00
Ethnicity               0.00
ParentalEducation       2.00
StudyTimeWeekly        19.83
Absences                7.00
Tutoring                1.00
ParentalSupport         2.00
Extracurricular         0.00
Sports                  0.00
Music                   1.00
Volunteering            0.00
GPA                     2.93
GradeClass              2.00
Name: 0, dtype: float64

In [25]:
df.iloc[0:5] 	#Display the lines 0 to 4

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0

In [28]:
df.loc [df['Age'] < 16] 	# conditional filtering

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
6,1007,15,0,1,1,15.60,10,0,3,0,1,0,0,2.75,2.0
7,1008,15,1,1,4,15.42,22,1,1,1,0,0,0,1.36,4.0
15,1016,15,0,0,2,9.73,17,1,0,0,1,0,0,1.34,4.0
21,1022,15,0,0,2,15.32,25,0,1,1,0,0,0,0.35,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2367,3368,15,1,3,1,9.38,18,0,3,0,0,1,0,1.45,1.0
2368,3369,15,0,0,4,6.68,3,0,2,0,0,1,1,3.16,1.0
2378,3379,15,1,0,2,12.91,26,0,2,0,0,1,1,0.71,3.0
2381,3382,15,0,2,0,10.10,5,0,3,0,0,0,0,2.96,0.0
2384,3385,15,1,0,1,16.66,13,1,3,0,1,0,0,2.54,4.0

In [31]:
df ['test'] = df ['GPA'] * df['GradeClass'] #add new colomn test

pd.reset_option('display.max_columns') # reset display option in default mode
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,test
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0,5.86
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0,3.04
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0,0.45
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0,6.16
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0,5.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0,0.00
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0,13.12
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0,2.28
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0,1.80
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0,2.14

In [32]:
df.drop ('test' , axis= 1 , inplace = True)

#axis=0 → remove rows
#axis=1 → remove columns
#inplace=True → performs the deletion directly in the DataFrame df
#If inplace=False (default), the method returns a new DataFrame without modifying df.

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0

In [33]:
df['GPA'].min()

0.0

In [34]:
df[df['GPA'] == df['GPA'].min()]

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
87,1088,15,0,2,1,8.03e-03,27,0,1,0,0,1,0,0.0,4.0
474,1475,17,1,1,2,1.44e+00,24,0,0,0,0,0,0,0.0,4.0
484,1485,15,1,0,3,7.67e-01,29,0,0,0,0,0,0,0.0,4.0
629,1630,17,1,0,0,2.14e+00,28,0,1,1,0,1,0,0.0,4.0
879,1880,15,0,0,2,7.95e+00,25,0,0,0,0,0,0,0.0,4.0
963,1964,17,0,0,4,5.76e+00,26,0,0,0,0,0,0,0.0,4.0
1286,2287,16,0,2,3,5.41e+00,26,0,0,0,0,0,0,0.0,4.0
1500,2501,17,1,1,1,2.87e+00,29,0,1,0,0,0,0,0.0,4.0
1512,2513,15,0,2,1,4.46e+00,27,0,1,0,0,0,0,0.0,4.0
1622,2623,16,0,1,1,2.53e+00,29,0,2,0,0,0,0,0.0,4.0
1724,2725,16,0,3,3,7.30e+00,27,0,0,0,0,0,0,0.0,4.0
1832,2833,18,1,1,1,9.96e+00,28,1,1,0,1,0,0,0.0,4.0
2124,3125,16,1,1,3,5.30e+00,27,0,0,0,1,0,0,0.0,4.0
2204,3205,15,1,2,1,2.37e-01,27,0,0,0,1,0,0,0.0,3.0
2219,3220,17,1,0,2,1.62e-01,29,0,2,0,0,0,0,0.0,1.0
2310,3311,16,1,1,1,1.13e-01,28,0,2,0,0,0,0,0.0,1.0

In [35]:
df.sort_values (by = 'GPA' , ascending = False)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
44,1045,18,1,0,1,18.92,1,1,3,1,1,0,0,4.0,0.0
442,1443,15,0,0,2,19.42,0,0,3,0,1,1,1,4.0,0.0
2028,3029,16,1,0,0,18.66,0,1,4,1,0,0,1,4.0,0.0
1919,2920,15,0,3,1,17.44,1,1,1,1,1,0,0,4.0,0.0
1705,2706,18,1,0,2,8.86,0,1,4,1,0,0,0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,1475,17,1,1,2,1.44,24,0,0,0,0,0,0,0.0,4.0
1500,2501,17,1,1,1,2.87,29,0,1,0,0,0,0,0.0,4.0
629,1630,17,1,0,0,2.14,28,0,1,1,0,1,0,0.0,4.0
2124,3125,16,1,1,3,5.30,27,0,0,0,1,0,0,0.0,4.0
1512,2513,15,0,2,1,4.46,27,0,1,0,0,0,0,0.0,4.0

### **WorkShop 2**

In [37]:
nb = df.isnull().sum()  # Count missing (null) values per column:
print(nb)

df [df.isnull().any (axis = 1)]

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

Empty DataFrame
Columns: [StudentID, Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering, GPA, GradeClass]
Index: []

In [39]:
df.loc[len(df)] = {
    'StudentID': 9999,
    'Age': 17,
    'Gender': 1,
    'Ethnicity': 0,
    'ParentalEducation': 2,
    'StudyTimeWeekly': 12.5,
    'Absences': 3,
    'Tutoring': 0,
    'ParentalSupport': 2,
    'Extracurricular': 1,
    'Sports': 0,
    'Music': 1,
    'Volunteering': 0,
    'GPA': 3.25,
    'GradeClass': 1.0
}

In [40]:
df.tail() 	# first 5 lines

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2389,3390.0,16.0,1.0,0.0,2.0,6.81,20.0,0.0,2.0,0.0,0.0,0.0,1.0,1.14,2.0
2390,3391.0,16.0,1.0,1.0,0.0,12.42,17.0,0.0,2.0,0.0,1.0,1.0,0.0,1.80,1.0
2391,3392.0,16.0,1.0,0.0,2.0,17.82,13.0,0.0,2.0,0.0,0.0,0.0,1.0,2.14,1.0
2392,9999.0,18.0,1.0,1.0,2.0,15.50,5.0,1.0,3.0,0.0,1.0,0.0,1.0,3.50,1.0
2393,9999.0,17.0,1.0,0.0,2.0,12.50,3.0,0.0,2.0,1.0,0.0,1.0,0.0,3.25,1.0

In [41]:
new_row = pd.DataFrame([{
    'StudentID': 9999,
    'Age': 17,
    'Gender': 1,
    'Ethnicity': 0,
    'ParentalEducation': 2,
    'StudyTimeWeekly': 12.5,
    'Absences': 3,
    'Tutoring': 0,
    'ParentalSupport': 2,
    'Extracurricular': 1,
    'Sports': 0,
    'Music': 1,
    'Volunteering': 0,
    'GPA': 3.25,
    'GradeClass': 1.0
}])

df = pd.concat([df, new_row], ignore_index=True)

In [42]:
df.tail() 	# first 5 lines

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2390,3391.0,16.0,1.0,1.0,0.0,12.42,17.0,0.0,2.0,0.0,1.0,1.0,0.0,1.80,1.0
2391,3392.0,16.0,1.0,0.0,2.0,17.82,13.0,0.0,2.0,0.0,0.0,0.0,1.0,2.14,1.0
2392,9999.0,18.0,1.0,1.0,2.0,15.50,5.0,1.0,3.0,0.0,1.0,0.0,1.0,3.50,1.0
2393,9999.0,17.0,1.0,0.0,2.0,12.50,3.0,0.0,2.0,1.0,0.0,1.0,0.0,3.25,1.0
2394,9999.0,17.0,1.0,0.0,2.0,12.50,3.0,0.0,2.0,1.0,0.0,1.0,0.0,3.25,1.0

In [43]:
import numpy as np
import pandas as pd

# Create 3 empty rows (all NaN) with the same columns as df
empty_rows = pd.DataFrame([{col: np.nan for col in df.columns} for _ in range(3)])

# Append them
df = pd.concat([df, empty_rows], ignore_index=True)

# Show last rows
print(df.tail(5))

      StudentID   Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
2393     9999.0  17.0     1.0        0.0                2.0             12.5
2394     9999.0  17.0     1.0        0.0                2.0             12.5
2395        NaN   NaN     NaN        NaN                NaN              NaN
2396        NaN   NaN     NaN        NaN                NaN              NaN
2397        NaN   NaN     NaN        NaN                NaN              NaN

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
2393       3.0       0.0              2.0              1.0     0.0    1.0
2394       3.0       0.0              2.0              1.0     0.0    1.0
2395       NaN       NaN              NaN              NaN     NaN    NaN
2396       NaN       NaN              NaN              NaN     NaN    NaN
2397       NaN       NaN              NaN              NaN     NaN    NaN

      Volunteering   GPA  GradeClass
2393           0.0  3.25         1.0
2394           0.0  3.25         1.0
2395           NaN   NaN         NaN
2396           NaN   NaN         NaN
2397           NaN   NaN         NaN

In [44]:
nb = df.isnull().sum()
print(nb)

df [df.isnull().any (axis = 1)]

StudentID            3
Age                  3
Gender               3
Ethnicity            3
ParentalEducation    3
StudyTimeWeekly      3
Absences             3
Tutoring             3
ParentalSupport      3
Extracurricular      3
Sports               3
Music                3
Volunteering         3
GPA                  3
GradeClass           3
dtype: int64

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df['GPA'] = df['GPA'].fillna(df['GPA'].mean())
#Fill mean for all numeric columns at once
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

df.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2393,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2394,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2395,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2396,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2397,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98

In [51]:
df = df.ffill()
# or
df = df.bfill()

In [52]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
df[['GPA']] = imputer.fit_transform(df[['GPA']])

df.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2393,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2394,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2395,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2396,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2397,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98

In [53]:
df = df.ffill()

df.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2393,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2394,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2395,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2396,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2397,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98

In [54]:
df = df.bfill()

df.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2393,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2394,9999.00,17.00,1.00,0.00,2.00,12.50,3.00,0.0,2.00,1.00,0.0,1.0,0.00,3.25,1.00
2395,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2396,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98
2397,2206.27,16.47,0.51,0.88,1.75,9.78,14.53,0.3,2.12,0.38,0.3,0.2,0.16,1.91,2.98

In [56]:
df.isnull().sum()                  # Count of NaNs per column
df[df['GPA'].isnull()]    # Rows where a specific column is NaN

Empty DataFrame
Columns: [StudentID, Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering, GPA, GradeClass]
Index: []

In [57]:
print(df.isnull().sum())  # Confirm all missing values are handled

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [58]:
# IQR method (example: outliers in GPA)

col = 'GPA'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

outliers_iqr = df[(df[col] < Q1 - 1.5 * IQR) | (df[col] > Q3 + 1.5 * IQR)]

print("IQR outliers count:", len(outliers_iqr))
outliers_iqr[[col]].head()

IQR outliers count: 0

Empty DataFrame
Columns: [GPA]
Index: []

In [59]:
from scipy.stats import zscore

col = 'GPA'

df['zscore'] = zscore(df[col].astype(float), nan_policy='omit')
outliers_z = df[df['zscore'].abs() > 3]

print("Z-score outliers count:", len(outliers_z))
outliers_z[[col, 'zscore']].head()

Z-score outliers count: 0

Empty DataFrame
Columns: [GPA, zscore]
Index: []

In [61]:
dup_id_count = df.duplicated(subset=['StudentID']).sum()
print("Duplicate StudentID rows:", dup_id_count)

df.drop_duplicates(subset=['StudentID'], keep='first', inplace=True)

Duplicate StudentID rows: 4

In [62]:
text_cols = df.select_dtypes(include="object").columns
print("Text columns:", list(text_cols))

Text columns: []

In [63]:
import numpy as np

# 1) Study efficiency: GPA per hour of weekly study (avoid divide-by-zero)
df["GPA_per_study_hour"] = df["GPA"] / df["StudyTimeWeekly"].replace(0, np.nan)

# 2) Attendance rate proxy: 1 = perfect attendance, lower = more absences
# (simple transform; tune the denominator if your Absences scale differs)
df["attendance_score"] = 1 / (1 + df["Absences"])

# 3) Total activities count (0–4) from binary columns
activity_cols = ["Extracurricular", "Sports", "Music", "Volunteering"]
df["activity_count"] = df[activity_cols].sum(axis=1)

# 4) Engagement score (example: tutoring + activities + parental support)
df["engagement_score"] = df["Tutoring"] + df["activity_count"] + df["ParentalSupport"]

df[["GPA","StudyTimeWeekly","GPA_per_study_hour","Absences","attendance_score",
    "activity_count","engagement_score"]].head()

,GPA,StudyTimeWeekly,GPA_per_study_hour,Absences,attendance_score,activity_count,engagement_score
0,2.93,19.83,0.15,7.0,0.12,1.0,4.0
1,3.04,15.41,0.20,0.0,1.00,0.0,1.0
2,0.11,4.21,0.03,26.0,0.04,0.0,2.0
3,2.05,10.03,0.20,14.0,0.07,1.0,4.0
4,1.29,4.67,0.28,17.0,0.06,0.0,4.0

In [64]:
# One-hot encode selected categorical columns (drop_first optional)
df_ohe = pd.get_dummies(
    df,
    columns=["Gender", "Ethnicity", "ParentalEducation", "GradeClass"],
    drop_first=False
)

df_ohe.head()

,StudentID,Age,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,...,ParentalEducation_1.7465553235908142,ParentalEducation_2.0,ParentalEducation_3.0,ParentalEducation_4.0,GradeClass_0.0,GradeClass_1.0,GradeClass_2.0,GradeClass_2.9812108559498958,GradeClass_3.0,GradeClass_4.0
0,1001.0,17.0,19.83,7.0,1.0,2.0,0.0,0.0,1.0,0.0,...,False,True,False,False,False,False,True,False,False,False
1,1002.0,18.0,15.41,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,True,False,False,False,False
2,1003.0,15.0,4.21,26.0,0.0,2.0,0.0,0.0,0.0,0.0,...,False,False,True,False,False,False,False,False,False,True
3,1004.0,17.0,10.03,14.0,0.0,3.0,1.0,0.0,0.0,0.0,...,False,False,True,False,False,False,False,False,True,False
4,1005.0,17.0,4.67,17.0,1.0,3.0,0.0,0.0,0.0,0.0,...,False,True,False,False,False,False,False,False,False,True

In [65]:
num_cols = [
    "Age", "StudyTimeWeekly", "Absences",
    "ParentalEducation", "ParentalSupport",
    "GPA"  # include only if it's a feature; exclude if it's your target
]

In [66]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score
0,1001.0,0.67,1.0,0.0,0.50,0.99,0.24,1.0,0.50,0.0,0.0,1.0,0.0,0.73,2.0,1.12,0.15,0.12,1.0,4.0
1,1002.0,1.00,0.0,0.0,0.25,0.77,0.00,0.0,0.25,0.0,0.0,0.0,0.0,0.76,1.0,1.24,0.20,1.00,0.0,1.0
2,1003.0,0.00,0.0,2.0,0.75,0.21,0.90,0.0,0.50,0.0,0.0,0.0,0.0,0.03,4.0,-1.96,0.03,0.04,0.0,2.0
3,1004.0,0.67,1.0,0.0,0.75,0.50,0.48,0.0,0.75,1.0,0.0,0.0,0.0,0.51,3.0,0.16,0.20,0.07,1.0,4.0
4,1005.0,0.67,1.0,0.0,0.50,0.23,0.59,1.0,0.75,0.0,0.0,0.0,0.0,0.32,4.0,-0.68,0.28,0.06,0.0,4.0

In [67]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score
0,1001.0,0.47,1.0,0.0,0.25,1.78,-0.89,1.0,-0.11,0.0,0.0,1.0,0.0,1.12,2.0,1.12,0.15,0.12,1.0,4.0
1,1002.0,1.36,0.0,0.0,-0.75,1.00,-1.72,0.0,-1.00,0.0,0.0,0.0,0.0,1.24,1.0,1.24,0.20,1.00,0.0,1.0
2,1003.0,-1.31,0.0,2.0,1.25,-0.98,1.35,0.0,-0.11,0.0,0.0,0.0,0.0,-1.96,4.0,-1.96,0.03,0.04,0.0,2.0
3,1004.0,0.47,1.0,0.0,1.25,0.05,-0.06,0.0,0.78,1.0,0.0,0.0,0.0,0.16,3.0,0.16,0.20,0.07,1.0,4.0
4,1005.0,0.47,1.0,0.0,0.25,-0.90,0.29,1.0,0.78,0.0,0.0,0.0,0.0,-0.68,4.0,-0.68,0.28,0.06,0.0,4.0

In [68]:
# 2) GPA should be between 0 and 4
bad_gpa = df[(df["GPA"] < 0) | (df["GPA"] > 4)]
print("Bad GPA rows:", len(bad_gpa))
bad_gpa[["StudentID", "GPA"]].head()

Bad GPA rows: 1206

    StudentID   GPA
2      1003.0 -1.96
4      1005.0 -0.68
7      1008.0 -0.60
11     1012.0 -0.38
12     1013.0 -0.42

### **workshop 3**

In [70]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [71]:
df.groupby("Gender")[["GPA", "StudyTimeWeekly", "Absences"]].mean()

             GPA  StudyTimeWeekly  Absences
Gender
0.00    1.29e-02        -1.21e-02 -2.15e-02
0.51    1.23e-03         4.03e-04 -1.14e-03
1.00   -1.24e-02         1.16e-02  2.06e-02

In [72]:
df.groupby("Ethnicity").mean(numeric_only=True)

,StudentID,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score,zscore_GPA
Ethnicity,,,,,,,,,,,,,,,,,,,,
0.00,2194.37,2.66e-02,0.51,-1.70e-02,-4.59e-03,3.19e-02,0.31,-2.15e-03,0.38,0.30,0.20,0.15,-3.38e-02,3.02,-0.04,-0.53,-3.24,1.04,3.47,-3.38e-02
0.88,2206.27,3.94e-04,0.51,2.12e-04,4.03e-04,-1.14e-03,0.30,-9.11e-05,0.38,0.30,0.20,0.16,1.23e-03,2.98,0.00,3.04,1.00,1.04,3.47,1.23e-03
1.00,2251.30,-3.75e-02,0.49,-2.37e-02,2.94e-02,-4.70e-02,0.29,-6.22e-02,0.43,0.30,0.18,0.15,4.67e-02,2.94,0.05,-0.26,-5.86,1.06,3.40,4.67e-02
2.00,2177.90,1.98e-02,0.52,6.85e-03,-6.44e-02,-1.17e-02,0.31,3.69e-02,0.37,0.32,0.20,0.18,1.67e-02,2.96,0.02,-10.59,-2.85,1.07,3.55,1.67e-02
3.00,2160.70,-1.05e-01,0.54,1.32e-01,9.58e-02,-4.38e-02,0.27,7.15e-02,0.35,0.27,0.18,0.16,4.46e-02,2.94,0.04,-1.14,-4.14,0.96,3.43,4.46e-02

In [73]:
df.groupby("GradeClass")["Absences"].sum()

GradeClass
0.00   -1.11e+02
1.00   -2.94e+02
2.00   -3.37e+02
2.98   -1.14e-03
3.00   -1.52e+02
4.00    8.94e+02
Name: Absences, dtype: float64

In [74]:
df.groupby("GradeClass").size()

GradeClass
0.00     107
1.00     270
2.00     391
2.98       1
3.00     414
4.00    1212
dtype: int64

In [75]:
df.groupby("Gender").count()

,StudentID,Age,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score,zscore_GPA
Gender,,,,,,,,,,,,,,,,,,,,
0.00,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170,1170
0.51,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1.00,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224,1224

In [76]:
print(df.columns.tolist())

['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass', 'zscore', 'GPA_per_study_hour', 'attendance_score', 'activity_count', 'engagement_score', 'zscore_GPA']

In [77]:
df.groupby(["Gender", "GradeClass"])[["GPA", "StudyTimeWeekly", "Absences"]].mean()

                        GPA  StudyTimeWeekly  Absences
Gender GradeClass
0.00   0.00        1.02e+00         3.28e-01 -7.78e-01
       1.00        1.22e+00         2.32e-01 -1.10e+00
       2.00        8.43e-01         3.00e-03 -9.02e-01
       3.00        3.56e-01        -1.90e-02 -4.06e-01
       4.00       -7.61e-01        -1.04e-01  7.29e-01
0.51   2.98        1.23e-03         4.03e-04 -1.14e-03
1.00   0.00        1.65e+00         4.16e-01 -1.35e+00
       1.00        1.18e+00         2.50e-01 -1.08e+00
       2.00        8.02e-01         1.15e-01 -8.19e-01
       3.00        3.19e-01         1.23e-02 -3.31e-01
       4.00       -7.65e-01        -1.04e-01  7.46e-01

In [78]:
df.groupby("GradeClass")["GPA"].mean().sort_values(ascending=False)

GradeClass
0.00    1.31e+00
1.00    1.20e+00
2.00    8.23e-01
3.00    3.37e-01
2.98    1.23e-03
4.00   -7.63e-01
Name: GPA, dtype: float64

In [79]:
df_ethnicity = pd.DataFrame({
    "Ethnicity": [0, 1, 2, 3],
    "EthnicityLabel": ["Group0", "Group1", "Group2", "Group3"]
})

merged_df = pd.merge(df, df_ethnicity, on="Ethnicity", how="left")
merged_df.head()

/tmp/ipykernel_7155/2804907673.py:6: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  merged_df = pd.merge(df, df_ethnicity, on="Ethnicity", how="left")

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,...,Volunteering,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score,zscore_GPA,EthnicityLabel
0,1001.0,0.47,1.0,0.0,0.25,1.78,-0.89,1.0,-0.11,0.0,...,0.0,1.12,2.0,1.12,0.63,9.13,1.0,4.0,1.12,Group0
1,1002.0,1.36,0.0,0.0,-0.75,1.00,-1.72,0.0,-1.00,0.0,...,0.0,1.24,1.0,1.24,1.24,-1.39,0.0,1.0,1.24,Group0
2,1003.0,-1.31,0.0,2.0,1.25,-0.98,1.35,0.0,-0.11,0.0,...,0.0,-1.96,4.0,-1.96,1.99,0.42,0.0,2.0,-1.96,Group2
3,1004.0,0.47,1.0,0.0,1.25,0.05,-0.06,0.0,0.78,1.0,...,0.0,0.16,3.0,0.16,3.58,1.07,1.0,4.0,0.16,Group0
4,1005.0,0.47,1.0,0.0,0.25,-0.90,0.29,1.0,0.78,0.0,...,0.0,-0.68,4.0,-0.68,0.75,0.77,0.0,4.0,-0.68,Group0

In [80]:
df_grade_info = pd.DataFrame({
    "grade_code": [0.0, 1.0, 2.0, 3.0, 4.0],
    "grade_label": ["A", "B", "C", "D", "F"]
})

merged_df2 = pd.merge(df, df_grade_info, left_on="GradeClass", right_on="grade_code", how="left")
merged_df2.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,...,GPA,GradeClass,zscore,GPA_per_study_hour,attendance_score,activity_count,engagement_score,zscore_GPA,grade_code,grade_label
0,1001.0,0.47,1.0,0.0,0.25,1.78,-0.89,1.0,-0.11,0.0,...,1.12,2.0,1.12,0.63,9.13,1.0,4.0,1.12,2.0,C
1,1002.0,1.36,0.0,0.0,-0.75,1.00,-1.72,0.0,-1.00,0.0,...,1.24,1.0,1.24,1.24,-1.39,0.0,1.0,1.24,1.0,B
2,1003.0,-1.31,0.0,2.0,1.25,-0.98,1.35,0.0,-0.11,0.0,...,-1.96,4.0,-1.96,1.99,0.42,0.0,2.0,-1.96,4.0,F
3,1004.0,0.47,1.0,0.0,1.25,0.05,-0.06,0.0,0.78,1.0,...,0.16,3.0,0.16,3.58,1.07,1.0,4.0,0.16,3.0,D
4,1005.0,0.47,1.0,0.0,0.25,-0.90,0.29,1.0,0.78,0.0,...,-0.68,4.0,-0.68,0.75,0.77,0.0,4.0,-0.68,4.0,F

---
# <center>🔬 Axis 3 : Exploratory Analysis & Statistics</center>

> **Goal:** Perform a thorough exploratory data analysis (EDA) on the student-performance dataset.  
> We will inspect the data structure, compute descriptive statistics, examine distributions,  
> measure relationships between variables, and run a one-way ANOVA to compare groups.

**Sub-sections**
1. Dataset overview (shape, dtypes, missing values)
2. Basic descriptive statistics
3. Variance analysis
4. Covariance & correlation matrices
5. Z-score normalisation
6. Distribution visualisations (histograms / KDE / boxplots)
7. One-way ANOVA
8. GroupBy aggregations & pivot table
---

## 1. Dataset Overview

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# ── Shape ──────────────────────────────────────────────────────────────────
print("Shape (rows × cols):", df.shape)

# ── Column dtypes ──────────────────────────────────────────────────────────
print("\nColumn dtypes:")
print(df.dtypes)

# ── Missing values ─────────────────────────────────────────────────────────
missing = df.isnull().sum()
print("\nMissing values per column:")
print(missing[missing > 0] if missing.any() else "No missing values ✔")

## 2. Basic Descriptive Statistics

In [ ]:
# Key numeric columns of interest
key_cols = ['GPA', 'StudyTimeWeekly', 'Absences']

print("=== Descriptive statistics for key columns ===")
print(df[key_cols].describe().round(4))

print("\n=== Mean ===")
print(df[key_cols].mean(numeric_only=True).round(4))

print("\n=== Median ===")
print(df[key_cols].median(numeric_only=True).round(4))

print("\n=== Std deviation ===")
print(df[key_cols].std(numeric_only=True).round(4))

print("\n=== Quartiles (Q1, Q2, Q3) ===")
print(df[key_cols].quantile([0.25, 0.50, 0.75]).round(4))

## 3. Variance Analysis

In [ ]:
# Variance for all numeric columns
variances = df.var(numeric_only=True).round(4)
print("Variance per numeric column:")
print(variances.sort_values(ascending=False))

# Identify the column with the highest variance
max_var_col = variances.idxmax()
print(f"\nColumn with highest variance: '{max_var_col}' (σ² = {variances[max_var_col]:.4f})")

## 4. Covariance & Correlation Matrices

In [ ]:
# ── Covariance matrix ──────────────────────────────────────────────────────
cov_matrix = df[key_cols].cov().round(4)
print("Covariance matrix:")
print(cov_matrix)

plt.figure(figsize=(7, 5))
sns.heatmap(cov_matrix, annot=True, fmt='.2f', cmap='Blues', linewidths=0.5)
plt.title('Covariance Matrix — Key Columns')
plt.tight_layout()
plt.show()

In [ ]:
# ── Correlation matrix (all numeric columns) ───────────────────────────────
corr_matrix = df.corr(numeric_only=True).round(4)
print("Correlation matrix:")
print(corr_matrix)

plt.figure(figsize=(10, 7))
sns.heatmap(
    corr_matrix,
    annot=True, fmt='.2f',
    cmap='coolwarm', center=0,
    linewidths=0.5, square=True
)
plt.title('Correlation Matrix — All Numeric Columns')
plt.tight_layout()
plt.show()

## 5. Z-score Normalisation

In [ ]:
from scipy.stats import zscore

# Select numeric columns only (drop any non-numeric)
num_cols = df.select_dtypes(include=np.number).columns.tolist()

# Apply z-score normalisation
df_zscore = df[num_cols].apply(zscore, nan_policy='omit')

print("Z-score normalised data (first 5 rows):")
print(df_zscore.head().round(4))

print("\nVariance after z-score normalisation (should be ≈ 1 for each column):")
print(df_zscore.var().round(4))

## 6. Distribution Visualisations

In [ ]:
# ── Histogram + KDE ────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

for ax, col in zip(axes, ['GPA', 'Absences', 'StudyTimeWeekly']):
    sns.histplot(df[col].dropna(), kde=True, ax=ax, color='steelblue', edgecolor='white')
    ax.set_title(f'Distribution of {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Count')

plt.suptitle('Histogram + KDE — Key Columns', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

In [ ]:
# ── Boxplots ───────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for ax, col in zip(axes, ['GPA', 'Absences', 'StudyTimeWeekly']):
    sns.boxplot(y=df[col].dropna(), ax=ax, color='lightcoral')
    ax.set_title(f'Boxplot — {col}')
    ax.set_ylabel(col)

plt.suptitle('Boxplots — Key Columns', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

## 7. One-Way ANOVA — GPA by Parental Education Level

> **Hypothesis**  
> H₀: Mean GPA is the same across all parental-education groups.  
> H₁: At least one group has a significantly different mean GPA.  
> Significance level: α = 0.05

In [ ]:
from scipy.stats import f_oneway

# Build one GPA array per ParentalEducation level
anova_col = 'ParentalEducation'
groups = [
    df[df[anova_col] == lvl]['GPA'].dropna().values
    for lvl in sorted(df[anova_col].unique())
]

# Report group sizes
print("Group sizes (ParentalEducation level → n):")
for lvl, grp in zip(sorted(df[anova_col].unique()), groups):
    print(f"  Level {lvl}: n = {len(grp)}, mean GPA = {grp.mean():.4f}")

# Run one-way ANOVA
f_stat, p_value = f_oneway(*groups)
print(f"\nF-statistic : {f_stat:.4f}")
print(f"p-value     : {p_value:.6f}")

alpha = 0.05
if p_value < alpha:
    print("\n→ Reject H₀: significant difference in mean GPA across parental-education groups.")
else:
    print("\n→ Fail to reject H₀: no significant difference in mean GPA across groups.")

In [ ]:
# Boxplot — GPA by ParentalEducation
plt.figure(figsize=(9, 5))
sns.boxplot(
    data=df,
    x='ParentalEducation', y='GPA',
    palette='Set2', order=sorted(df['ParentalEducation'].unique())
)
plt.title('GPA Distribution by Parental Education Level')
plt.xlabel('Parental Education Level')
plt.ylabel('GPA')
plt.tight_layout()
plt.show()

## 8. GroupBy Aggregations & Pivot Table

In [ ]:
# Mean GPA by ParentalSupport level
print("Mean GPA by Parental Support level:")
gpa_by_support = (
    df.groupby('ParentalSupport')['GPA']
    .mean()
    .round(4)
    .rename_axis('ParentalSupport')
    .reset_index(name='Mean_GPA')
)
print(gpa_by_support.to_string(index=False))

In [ ]:
# Pivot table — mean GPA by ParentalEducation (rows) × Gender (columns)
pivot = pd.pivot_table(
    df,
    values='GPA',
    index='ParentalEducation',
    columns='Gender',
    aggfunc='mean'
).round(4)

print("Pivot table — Mean GPA by ParentalEducation × Gender:")
print(pivot)

## Axis III — Predictive Modeling & Deep Learning (on this student dataset)

This section applies the requested workflow (dataset preparation, regression, classification, advanced models, deep learning, interpretability, and backup) directly to `df` from this notebook.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    r2_score, mean_squared_error,
    accuracy_score, classification_report, confusion_matrix
)

import joblib

In [ ]:
# Targets for this dataset
# Regression target: GPA
# Classification target: is_high_performer (1 if GPA >= 3.0 else 0)
df_model = df.copy()
df_model['is_high_performer'] = (df_model['GPA'] >= 3.0).astype(int)

# Build features while avoiding leakage
excluded_cols = ['StudentID', 'GPA', 'GradeClass', 'is_high_performer']
X = df_model.drop(columns=[c for c in excluded_cols if c in df_model.columns], errors='ignore')
y_reg = df_model['GPA']
y_cls = df_model['is_high_performer']

categorical = X.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
numerical = X.select_dtypes(exclude=['object', 'category', 'bool']).columns.tolist()

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical)
])

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X, y_reg, test_size=0.2, random_state=42
)

X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X, y_cls, test_size=0.2, random_state=42, stratify=y_cls
)

print('X shape:', X.shape)
print('Regression target mean:', y_reg.mean().round(3))
print('Classification balance:')
print(y_cls.value_counts(normalize=True).round(3))

In [ ]:
# 6.2 Regression Models
reg_models = {
    'LinearRegression': LinearRegression(),
    'RandomForestRegressor': RandomForestRegressor(random_state=42),
    'Ridge': Ridge(),
    'Lasso': Lasso()
}

reg_results = []
reg_predictions = {}
reg_pipelines = {}

for name, model in reg_models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('regressor', model)
    ])
    pipe.fit(X_train_reg, y_train_reg)
    preds = pipe.predict(X_test_reg)

    reg_pipelines[name] = pipe
    reg_predictions[name] = preds
    reg_results.append({
        'Model': name,
        'R2': r2_score(y_test_reg, preds),
        'MSE': mean_squared_error(y_test_reg, preds)
    })

reg_results_df = pd.DataFrame(reg_results).sort_values('R2', ascending=False)
print(reg_results_df)

best_reg_name = reg_results_df.iloc[0]['Model']
best_reg_preds = reg_predictions[best_reg_name]

plt.figure(figsize=(7, 5))
sns.scatterplot(x=y_test_reg, y=best_reg_preds)
plt.plot([y_test_reg.min(), y_test_reg.max()], [y_test_reg.min(), y_test_reg.max()], 'r--')
plt.xlabel('Actual GPA')
plt.ylabel(f'Predicted GPA ({best_reg_name})')
plt.title(f'Actual vs Predicted GPA - {best_reg_name}')
plt.grid(True)
plt.show()

In [ ]:
# Cross-validation on linear baseline
pipe_lr = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', LinearRegression())
])

cv_scores = cross_val_score(pipe_lr, X, y_reg, cv=5, scoring='r2')
print('Cross-validated R² scores:', np.round(cv_scores, 4))
print('Mean CV R²:', cv_scores.mean().round(4))

In [ ]:
# 6.3 Classification Models
cls_models = {
    'LogisticRegression': LogisticRegression(max_iter=1000),
    'SVC': SVC(),
    'KNN': KNeighborsClassifier()
}

cls_results = []
cls_predictions = {}
cls_pipelines = {}

for name, model in cls_models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('classifier', model)
    ])
    pipe.fit(X_train_cls, y_train_cls)
    preds = pipe.predict(X_test_cls)

    cls_pipelines[name] = pipe
    cls_predictions[name] = preds

    acc = accuracy_score(y_test_cls, preds)
    cls_results.append({'Model': name, 'Accuracy': acc})

    print(f'\n{name} Accuracy: {acc:.4f}')
    print(classification_report(y_test_cls, preds))

cls_results_df = pd.DataFrame(cls_results).sort_values('Accuracy', ascending=False)
print('\nClassification summary:')
print(cls_results_df)


def plot_confusion(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(4, 3))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(title)
    plt.show()

for model_name, model_preds in cls_predictions.items():
    plot_confusion(y_test_cls, model_preds, f'Confusion Matrix - {model_name}')

In [ ]:
# 6.4 Advanced Methods (RandomForest, XGBoost, LightGBM)
advanced_reg_results = []
advanced_reg_models = {
    'RandomForestRegressor': RandomForestRegressor(random_state=42)
}

try:
    from xgboost import XGBRegressor
    advanced_reg_models['XGBRegressor'] = XGBRegressor(
        random_state=42,
        n_estimators=200,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9
    )
except Exception as e:
    print('XGBoost regressor unavailable:', e)

try:
    from lightgbm import LGBMRegressor
    advanced_reg_models['LGBMRegressor'] = LGBMRegressor(random_state=42)
except Exception as e:
    print('LightGBM regressor unavailable:', e)

for name, model in advanced_reg_models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('regressor', model)
    ])
    pipe.fit(X_train_reg, y_train_reg)
    preds = pipe.predict(X_test_reg)
    advanced_reg_results.append({
        'Model': name,
        'R2': r2_score(y_test_reg, preds),
        'MSE': mean_squared_error(y_test_reg, preds)
    })

print(pd.DataFrame(advanced_reg_results).sort_values('R2', ascending=False))

In [ ]:
advanced_cls_results = []
advanced_cls_predictions = {}
advanced_cls_models = {
    'RandomForestClassifier': RandomForestClassifier(random_state=42)
}

try:
    from xgboost import XGBClassifier
    advanced_cls_models['XGBClassifier'] = XGBClassifier(
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42
    )
except Exception as e:
    print('XGBoost classifier unavailable:', e)

try:
    from lightgbm import LGBMClassifier
    advanced_cls_models['LGBMClassifier'] = LGBMClassifier(random_state=42)
except Exception as e:
    print('LightGBM classifier unavailable:', e)

for name, model in advanced_cls_models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('classifier', model)
    ])
    pipe.fit(X_train_cls, y_train_cls)
    preds = pipe.predict(X_test_cls)
    advanced_cls_predictions[name] = preds

    acc = accuracy_score(y_test_cls, preds)
    advanced_cls_results.append({'Model': name, 'Accuracy': acc})

    print(f'\n{name} Accuracy: {acc:.4f}')
    print(classification_report(y_test_cls, preds))

print(pd.DataFrame(advanced_cls_results).sort_values('Accuracy', ascending=False))

for model_name, model_preds in advanced_cls_predictions.items():
    plot_confusion(y_test_cls, model_preds, f'Confusion Matrix - {model_name}')

In [ ]:
# 6.5 Introduction to Deep Learning (Keras dense networks)
X_all_processed = preprocessor.fit_transform(X)

if hasattr(X_all_processed, 'toarray'):
    X_all_processed = X_all_processed.toarray()

X_train_nn_reg, X_test_nn_reg, y_train_nn_reg, y_test_nn_reg = train_test_split(
    X_all_processed, y_reg, test_size=0.2, random_state=42
)

X_train_nn_cls, X_test_nn_cls, y_train_nn_cls, y_test_nn_cls = train_test_split(
    X_all_processed, y_cls, test_size=0.2, random_state=42, stratify=y_cls
)

print('NN train shape (regression):', X_train_nn_reg.shape)
print('NN train shape (classification):', X_train_nn_cls.shape)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Regression neural network
model_reg = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_nn_reg.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

model_reg.compile(optimizer='adam', loss='mse', metrics=['mae'])
history_reg = model_reg.fit(
    X_train_nn_reg, y_train_nn_reg,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    verbose=0
)

loss_reg, mae_reg = model_reg.evaluate(X_test_nn_reg, y_test_nn_reg, verbose=0)
preds_nn_reg = model_reg.predict(X_test_nn_reg, verbose=0).ravel()

print(f'NN Regression Test MSE: {loss_reg:.4f}')
print(f'NN Regression Test MAE: {mae_reg:.4f}')
print(f'NN Regression R²: {r2_score(y_test_nn_reg, preds_nn_reg):.4f}')

In [ ]:
# Classification neural network
model_cls = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_nn_cls.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_cls.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history_cls = model_cls.fit(
    X_train_nn_cls, y_train_nn_cls,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    verbose=0
)

loss_cls, acc_cls = model_cls.evaluate(X_test_nn_cls, y_test_nn_cls, verbose=0)
probs_nn_cls = model_cls.predict(X_test_nn_cls, verbose=0).ravel()
preds_nn_cls = (probs_nn_cls > 0.5).astype(int)

print(f'NN Classification Test Loss: {loss_cls:.4f}')
print(f'NN Classification Test Accuracy: {acc_cls:.4f}')
print(classification_report(y_test_nn_cls, preds_nn_cls))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_cls.history['loss'], label='Train Loss')
plt.plot(history_cls.history['val_loss'], label='Validation Loss')
plt.title('NN Classification Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_cls.history['accuracy'], label='Train Accuracy')
plt.plot(history_cls.history['val_accuracy'], label='Validation Accuracy')
plt.title('NN Classification Accuracy')
plt.legend()
plt.show()

plot_confusion(y_test_nn_cls, preds_nn_cls, 'Confusion Matrix - Neural Network')

In [ ]:
# 6.6 Advanced evaluation, interpretability (SHAP), backup
# SHAP on the best tree-based regression model if available.
try:
    import shap

    tree_candidates = ['RandomForestRegressor', 'XGBRegressor', 'LGBMRegressor']
    selected_tree = next((m for m in tree_candidates if m in advanced_reg_models), None)

    if selected_tree is not None:
        tree_pipe = Pipeline([
            ('preprocess', preprocessor),
            ('regressor', advanced_reg_models[selected_tree])
        ])
        tree_pipe.fit(X_train_reg, y_train_reg)

        X_train_proc = tree_pipe.named_steps['preprocess'].transform(X_train_reg)
        X_test_proc = tree_pipe.named_steps['preprocess'].transform(X_test_reg)

        if hasattr(X_train_proc, 'toarray'):
            X_train_proc = X_train_proc.toarray()
            X_test_proc = X_test_proc.toarray()

        explainer = shap.Explainer(tree_pipe.named_steps['regressor'], X_train_proc)
        shap_values = explainer(X_test_proc[:100])
        shap.plots.beeswarm(shap_values)
    else:
        print('No tree model available for SHAP analysis.')

except Exception as e:
    print('SHAP analysis skipped:', e)

# Backup best baseline models
best_reg_model_name = reg_results_df.iloc[0]['Model']
best_cls_model_name = cls_results_df.iloc[0]['Model']

joblib.dump(reg_pipelines[best_reg_model_name], 'best_regression_model.joblib')
joblib.dump(cls_pipelines[best_cls_model_name], 'best_classification_model.joblib')

print('Saved models: best_regression_model.joblib, best_classification_model.joblib')

In [ ]:
# 6.7 Optional AutoML with PyCaret (run only if PyCaret is installed)
try:
    from pycaret.regression import setup as pc_setup, compare_models as pc_compare, save_model as pc_save

    automl_df = df_model.copy()

    reg_setup = pc_setup(
        data=automl_df,
        target='GPA',
        ignore_features=[c for c in ['StudentID', 'GradeClass', 'is_high_performer'] if c in automl_df.columns],
        session_id=123,
        verbose=False
    )

    best_automl_model = pc_compare()
    pc_save(best_automl_model, 'automl_gpa_model')
    print('PyCaret model trained and saved as automl_gpa_model')

except Exception as e:
    print('PyCaret section skipped:', e)