<a href="https://colab.research.google.com/github/hfeteh/hfeteh/blob/main/Students_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Student_performance_data _.csv to Student_performance_data _.csv

In [3]:
import pandas as pd
df = pd.read_csv('Student_performance_data _.csv')

In [4]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [5]:
df.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
5,1006,18,0,0,1,8.191219,0,0,1,1,0,0,0,3.084184,1.0
6,1007,15,0,1,1,15.601680,10,0,3,0,1,0,0,2.748237,2.0
7,1008,15,1,1,4,15.424496,22,1,1,1,0,0,0,1.360143,4.0
8,1009,17,0,0,0,4.562008,1,0,2,0,1,0,1,2.896819,2.0
9,1010,16,1,0,1,18.444466,0,0,3,1,0,0,0,3.573474,0.0

In [6]:
df.tail(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2382,3383,16,0,0,3,13.941823,20,0,2,0,0,0,0,1.191929,3.0
2383,3384,16,1,2,2,11.736409,18,1,4,0,0,0,0,1.810038,3.0
2384,3385,15,1,0,1,16.655581,13,1,3,0,1,0,0,2.539113,4.0
2385,3386,16,1,0,1,1.445434,20,0,3,1,1,0,0,1.395631,1.0
2386,3387,16,0,0,2,13.814021,14,0,2,0,0,0,0,2.000084,4.0
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [8]:
df.describe()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000
mean,2196.500000,16.468645,0.510870,0.877508,1.746237,9.771992,14.541388,0.301421,2.122074,0.383361,0.303512,0.196906,0.157191,1.906186,2.983696
std,690.655244,1.123798,0.499986,1.028476,1.000411,5.652774,8.467417,0.458971,1.122813,0.486307,0.459870,0.397744,0.364057,0.915156,1.233908
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1598.750000,15.000000,0.000000,0.000000,1.000000,5.043079,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.174803,2.000000
50%,2196.500000,16.000000,1.000000,0.000000,2.000000,9.705363,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.893393,4.000000
75%,2794.250000,17.000000,1.000000,2.000000,2.000000,14.408410,22.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.622216,4.000000
max,3392.000000,18.000000,1.000000,3.000000,4.000000,19.978094,29.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000

In [9]:
df.describe().round(2)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.00,2392.0,2392.00,2392.00,2392.00
mean,2196.50,16.47,0.51,0.88,1.75,9.77,14.54,0.30,2.12,0.38,0.30,0.2,0.16,1.91,2.98
std,690.66,1.12,0.50,1.03,1.00,5.65,8.47,0.46,1.12,0.49,0.46,0.4,0.36,0.92,1.23
min,1001.00,15.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
25%,1598.75,15.00,0.00,0.00,1.00,5.04,7.00,0.00,1.00,0.00,0.00,0.0,0.00,1.17,2.00
50%,2196.50,16.00,1.00,0.00,2.00,9.71,15.00,0.00,2.00,0.00,0.00,0.0,0.00,1.89,4.00
75%,2794.25,17.00,1.00,2.00,2.00,14.41,22.00,1.00,3.00,1.00,1.00,0.0,0.00,2.62,4.00
max,3392.00,18.00,1.00,3.00,4.00,19.98,29.00,1.00,4.00,1.00,1.00,1.0,1.00,4.00,4.00

In [10]:
df.sample(3)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
731,1732,15,0,0,2,15.921371,27,0,2,0,1,0,0,1.084490,4.0
61,1062,17,0,0,1,17.376022,12,0,2,0,0,1,0,2.331262,3.0
2264,3265,16,0,2,1,3.423695,27,0,3,1,0,0,0,0.557549,2.0

In [11]:
df.shape

(2392, 15)

In [12]:
df.columns          	# column names

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [13]:
print(df.columns)

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [14]:
df.dtypes             	# types of each column

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

In [17]:
df['Gender']  #display column of brand

0       1
1       0
2       0
3       1
4       1
       ..
2387    1
2388    0
2389    1
2390    1
2391    1
Name: Gender, Length: 2392, dtype: int64

In [19]:
df['Age'].value_counts()       	# frequency of values

Age
15    630
16    593
17    587
18    582
Name: count, dtype: int64

In [20]:
df ['Age'].nunique()            	# number of unique values

4

In [21]:
pd.set_option('display.max_columns',None) # display all columns

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [22]:
pd.set_option('display.precision',2) # number of decimal places

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0

In [23]:
df ['Age'] 	# single column

0       17
1       18
2       15
3       17
4       17
        ..
2387    18
2388    17
2389    16
2390    16
2391    16
Name: Age, Length: 2392, dtype: int64

In [24]:
df.iloc[0] 	#dIsplay the first line

StudentID            1001.00
Age                    17.00
Gender                  1.00
Ethnicity               0.00
ParentalEducation       2.00
StudyTimeWeekly        19.83
Absences                7.00
Tutoring                1.00
ParentalSupport         2.00
Extracurricular         0.00
Sports                  0.00
Music                   1.00
Volunteering            0.00
GPA                     2.93
GradeClass              2.00
Name: 0, dtype: float64

In [25]:
df.iloc[0:5] 	#Display the lines 0 to 4

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0

In [28]:
df.loc [df['Age'] < 16] 	# conditional filtering

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
6,1007,15,0,1,1,15.60,10,0,3,0,1,0,0,2.75,2.0
7,1008,15,1,1,4,15.42,22,1,1,1,0,0,0,1.36,4.0
15,1016,15,0,0,2,9.73,17,1,0,0,1,0,0,1.34,4.0
21,1022,15,0,0,2,15.32,25,0,1,1,0,0,0,0.35,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2367,3368,15,1,3,1,9.38,18,0,3,0,0,1,0,1.45,1.0
2368,3369,15,0,0,4,6.68,3,0,2,0,0,1,1,3.16,1.0
2378,3379,15,1,0,2,12.91,26,0,2,0,0,1,1,0.71,3.0
2381,3382,15,0,2,0,10.10,5,0,3,0,0,0,0,2.96,0.0
2384,3385,15,1,0,1,16.66,13,1,3,0,1,0,0,2.54,4.0

In [31]:
df ['test'] = df ['GPA'] * df['GradeClass'] #add new colomn test

pd.reset_option('display.max_columns') # reset display option in default mode
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,test
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0,5.86
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0,3.04
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0,0.45
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0,6.16
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0,5.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0,0.00
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0,13.12
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0,2.28
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0,1.80
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0,2.14

In [32]:
df.drop ('test' , axis= 1 , inplace = True)

#axis=0 → remove rows
#axis=1 → remove columns
#inplace=True → performs the deletion directly in the DataFrame df
#If inplace=False (default), the method returns a new DataFrame without modifying df.

df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,2,0,0,1,0,2.93,2.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.04,1.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,0.11,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.05,3.0
4,1005,17,1,0,2,4.67,17,1,3,0,0,0,0,1.29,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.68,2,0,4,1,0,0,0,3.46,0.0
2388,3389,17,0,0,1,7.58,4,1,4,0,1,0,0,3.28,4.0
2389,3390,16,1,0,2,6.81,20,0,2,0,0,0,1,1.14,2.0
2390,3391,16,1,1,0,12.42,17,0,2,0,1,1,0,1.80,1.0
2391,3392,16,1,0,2,17.82,13,0,2,0,0,0,1,2.14,1.0

In [33]:
df['GPA'].min()

0.0

In [34]:
df[df['GPA'] == df['GPA'].min()]

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
87,1088,15,0,2,1,8.03e-03,27,0,1,0,0,1,0,0.0,4.0
474,1475,17,1,1,2,1.44e+00,24,0,0,0,0,0,0,0.0,4.0
484,1485,15,1,0,3,7.67e-01,29,0,0,0,0,0,0,0.0,4.0
629,1630,17,1,0,0,2.14e+00,28,0,1,1,0,1,0,0.0,4.0
879,1880,15,0,0,2,7.95e+00,25,0,0,0,0,0,0,0.0,4.0
963,1964,17,0,0,4,5.76e+00,26,0,0,0,0,0,0,0.0,4.0
1286,2287,16,0,2,3,5.41e+00,26,0,0,0,0,0,0,0.0,4.0
1500,2501,17,1,1,1,2.87e+00,29,0,1,0,0,0,0,0.0,4.0
1512,2513,15,0,2,1,4.46e+00,27,0,1,0,0,0,0,0.0,4.0
1622,2623,16,0,1,1,2.53e+00,29,0,2,0,0,0,0,0.0,4.0
1724,2725,16,0,3,3,7.30e+00,27,0,0,0,0,0,0,0.0,4.0
1832,2833,18,1,1,1,9.96e+00,28,1,1,0,1,0,0,0.0,4.0
2124,3125,16,1,1,3,5.30e+00,27,0,0,0,1,0,0,0.0,4.0
2204,3205,15,1,2,1,2.37e-01,27,0,0,0,1,0,0,0.0,3.0
2219,3220,17,1,0,2,1.62e-01,29,0,2,0,0,0,0,0.0,1.0
2310,3311,16,1,1,1,1.13e-01,28,0,2,0,0,0,0,0.0,1.0

In [35]:
df.sort_values (by = 'GPA' , ascending = False)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
44,1045,18,1,0,1,18.92,1,1,3,1,1,0,0,4.0,0.0
442,1443,15,0,0,2,19.42,0,0,3,0,1,1,1,4.0,0.0
2028,3029,16,1,0,0,18.66,0,1,4,1,0,0,1,4.0,0.0
1919,2920,15,0,3,1,17.44,1,1,1,1,1,0,0,4.0,0.0
1705,2706,18,1,0,2,8.86,0,1,4,1,0,0,0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,1475,17,1,1,2,1.44,24,0,0,0,0,0,0,0.0,4.0
1500,2501,17,1,1,1,2.87,29,0,1,0,0,0,0,0.0,4.0
629,1630,17,1,0,0,2.14,28,0,1,1,0,1,0,0.0,4.0
2124,3125,16,1,1,3,5.30,27,0,0,0,1,0,0,0.0,4.0
1512,2513,15,0,2,1,4.46,27,0,1,0,0,0,0,0.0,4.0

### **WorkShop 2**

In [37]:
nb = df.isnull().sum()  # Count missing (null) values per column:
print(nb)

df [df.isnull().any (axis = 1)]

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

Empty DataFrame
Columns: [StudentID, Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering, GPA, GradeClass]
Index: []